site_name: Beezig Wiki
nav:
    - Home: index.md
    - Installation: installation.md
    - Settings:  settings.md
    - Commands: commands.md
    - Modules: modules.md

theme:
  name: material
  theme_dir: 'mkdocs-material/material'
  logo: 'images/news.png'
  favicon: 'images/logo.png'
  palette:
    primary: 'cyan'
    accent: 'light blue'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Beezig'
    - type: 'twitter'
      link: 'https://twitter.com/RealRoccoDev'
    - type: 'twitter'
      link: 'https://twitter.com/ItsNiklass'

copyright: 'Copyright &copy; 2019 Beezig Team'

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
